import { test, expect } from '../fixtures'
import { mockWordset, selectWords, readWordset, finishSession } from '../fixtures/practice'

test('desktop loads the real wordset and exposes game controls', async ({ wordsPage, page }) => {
    await wordsPage.goto()
    await expect(page).toHaveURL('/words')
    await expect(page.getByTestId('question-display')).not.toBeEmpty()
    await expect(page.getByRole('textbox')).toBeEditable()
    await expect(page.getByTestId('settings-trigger').filter({ visible: true })).toBeVisible()
    await expect(page.getByTestId('stats-display')).toContainText('Score')
})

test('correct and incorrect answers lock the input and advance with cleared feedback', async ({ wordsPage, page }) => {
    await mockWordset(page)
    await wordsPage.goto()
    await expect(page.getByTestId('question-display')).toHaveText('あいう')
    const input = page.getByRole('textbox')
    await input.fill('aiu')
    await input.press('Enter')
    await expect(input).toHaveClass(/border-success/)
    await expect(input).toHaveAttribute('readonly', '')
    const next = page.getByRole('button', { name: 'Next Word', exact: true })
    await next.click()
    await expect(input).toBeEditable()
    await expect(input).toHaveValue('')
    await expect(next).toBeHidden()
    await input.fill('wronganswer')
    await page.getByRole('button', { name: 'Check', exact: true }).click()
    await expect(input).toHaveClass(/border-destructive/)
    await expect(input).toHaveAttribute('readonly', '')
    await expect(next).toBeVisible()
})

test('mobile downloads the real payload only after consent and saves it', async ({ page }) => {
    test.setTimeout(60_000)
    await page.setViewportSize({ width: 390, height: 844 })
    let downloads = 0
    page.on('request', request => {
        if (/\/wordsets\/(en|es)-[a-f0-9]{64}\.json$/.test(new URL(request.url()).pathname) && request.method() === 'GET') downloads++
    })
    await page.goto('/words')
    await expect(page.getByRole('textbox')).toBeEditable()
    await selectWords(page)
    const modal = page.getByTestId('mobile-wordset-modal')
    await expect(modal).toBeVisible()
    expect(downloads).toBe(0)
    await modal.getByRole('button', { name: 'Download', exact: true }).click()
    await expect(modal).toBeHidden({ timeout: 30_000 })
    await expect(page.getByRole('textbox')).toBeEditable()
    const saved = await readWordset(page) as { hiraganaWords: unknown[] }
    expect(saved.hiraganaWords.length).toBeGreaterThan(100)
    expect(downloads).toBe(1)
})

test('Guess mode offers three choices and locks them after an answer', async ({ wordsPage, page }) => {
    await mockWordset(page)
    await wordsPage.goto()
    await page.getByTestId('settings-trigger').filter({ visible: true }).click()
    const settings = page.getByRole('dialog', { name: 'Practice Settings', exact: true })
    await settings.getByRole('button', { name: 'Guess the Char Multiple choice', exact: true }).click()
    await settings.getByRole('button', { name: 'Save Settings', exact: true }).click()
    await expect(settings).toBeHidden()
    await expect(page.getByRole('textbox')).toBeHidden()
    const options = page.getByTestId('guess-option')
    await expect(options).toHaveCount(3)
    await options.first().click()
    for (const option of await options.all()) await expect(option).toBeDisabled()
    await page.getByRole('button', { name: 'Next Word', exact: true }).click()
    await expect(options.first()).toBeEnabled()
})

test('completes exactly five words and restarts with an empty editable answer', async ({ wordsPage, page }) => {
    await mockWordset(page)
    await wordsPage.goto()
    await page.getByTestId('settings-trigger').filter({ visible: true }).click()
    const settings = page.getByRole('dialog', { name: 'Practice Settings', exact: true })
    await settings.getByRole('button', { name: 'Session', exact: true }).click()
    await settings.getByRole('button', { name: '5', exact: true }).click()
    await settings.getByRole('button', { name: 'Save Settings', exact: true }).click()
    await expect(settings).toBeHidden()
    await expect(page.getByTestId('stats-display')).toContainText('5 rounds left')
    await finishSession(page, async () => {
        await page.getByRole('textbox').fill('aiu')
        await page.getByRole('textbox').press('Enter')
    }, 'Next Word')
    await expect(page.getByRole('textbox')).toBeEditable()
    await expect(page.getByRole('textbox')).toHaveValue('')
})


test('settings cancel and unchanged Apply preserve the question; Custom has loaded filters', async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 1280, height: 1000 })
    await mockWordset(page)
    await page.goto('/words')
    const input = page.getByRole('textbox')
    await expect(page.getByTestId('question-display')).toHaveText('あいう')
    await input.fill('partial')
    const trigger = page.getByTestId('settings-trigger').filter({ visible: true })
    await trigger.click()
    const dialog = page.getByRole('dialog', { name: 'Practice Settings', exact: true })
    await dialog.getByRole('button', { name: '20', exact: true }).click()
    await page.keyboard.press('Escape')
    await expect(dialog).toBeHidden()
    await expect(input).toHaveValue('partial')
    await trigger.click()
    await dialog.getByRole('button', { name: 'Save Settings', exact: true }).click()
    await expect(dialog).toBeHidden()
    await expect(input).toHaveValue('partial')
    await expect(page.getByTestId('stats-display')).toContainText('10 rounds left')
    await trigger.click()
    await dialog.getByRole('button', { name: /Custom/ }).click()
    await dialog.getByRole('button', { name: 'Deselect all', exact: true }).click()
    await expect(dialog.getByRole('button', { name: 'Save Settings', exact: true })).toBeDisabled()
    await dialog.getByRole('button', { name: 'Select all', exact: true }).click()
    await expect(dialog.getByRole('button', { name: 'Save Settings', exact: true })).toBeEnabled()
    await dialog.getByRole('button', { name: 'あ', exact: true }).scrollIntoViewIfNeeded()
    await expect(dialog.getByRole('button', { name: 'あ', exact: true })).toBeInViewport({ ratio: 0.99 })
    await testInfo.attach('lifecycle-settings', { body: await page.screenshot({ fullPage: true }), contentType: 'image/png' })
    await dialog.getByRole('button', { name: 'Save Settings', exact: true }).click()
    await expect(input).toBeEditable()
    await expect(input).toHaveValue('')
    await expect(page.getByTestId('question-display')).not.toBeEmpty()
})
